-- 002_normalize_schema.sql

-- 1. Create Locations Table
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id TEXT REFERENCES patients(id) ON DELETE CASCADE,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    address TEXT,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

alter publication supabase_realtime add table locations;

-- 2. Create Alerts Table
CREATE TABLE IF NOT EXISTS alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id TEXT REFERENCES patients(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- 'Wandering', 'Fall Detected', 'Heart Rate'
    severity TEXT NOT NULL, -- 'Low', 'Medium', 'High'
    status TEXT NOT NULL DEFAULT 'Active', -- 'Active', 'Acknowledged', 'Resolved'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    resolved_at TIMESTAMP WITH TIME ZONE
);

alter publication supabase_realtime add table alerts;

-- 3. Migrate existing JSON data (Optional/Advanced, but better to start fresh for this task)
-- We will just ensure the tables exist.

-- 4. Enable RLS
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies (Public for demo)
CREATE POLICY "Public Read Locations" ON locations FOR SELECT USING (true);
CREATE POLICY "Public Insert Locations" ON locations FOR INSERT WITH CHECK (true);

CREATE POLICY "Public Read Alerts" ON alerts FOR SELECT USING (true);
CREATE POLICY "Public Insert Alerts" ON alerts FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Alerts" ON alerts FOR UPDATE USING (true);

-- 6. Insert Mock Data for testing
INSERT INTO locations (patient_id, lat, lng, address)
VALUES ('P001', 27.7172, 85.3240, 'Baluwatar, Kathmandu');

INSERT INTO alerts (patient_id, type, severity, status)
VALUES ('P001', 'Wandering Alert', 'High', 'Resolved');

-- 7. Note: We are NOT dropping columns from 'patients' immediately to prevent breaking existing code during migration phases,
-- but the App should now assume 'patients.location' is deprecated.
